name: OWASP ZAP Security Scan

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  extract-url-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Test URL from PR description
        id: get-url
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testUrl = `https://devopsdrops.tech/syncproxy?url=https://${headBranch}--eds--jhuckins.aem.page`;
            core.setOutput('test-url', testUrl);

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ steps.get-url.outputs.test-url }}
